# -*- coding: utf-8 -*-
"""Аналитика заказов v1.2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KA4Wuv0O3uSAbABAPl5fTd8BMNlSI_Mk
"""

from google.colab import files
uploaded = files.upload()

from google.colab import files
import pandas as pd
import numpy as np
import re
import os
from datetime import datetime

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1200)

# ----------- Параметры -----------
INPUT_XLSX = '/content/заказы 2025г. (обновлено 02.02.2026г.).xlsx'
OUTPUT_XLSX = 'аналитика_заказов_отчет.xlsx'
INDUSTRY_LOOKUP = '/content/industry_lookup.csv'

# Шаблоны
FEST_PATTERNS = [r'фонтанка\s*фест', r'фонтaнка\s*фест', r'фонтанка[-\s]*фест']
PROGRAMMATIC_PATTERNS = [
    r'программатик\s*фонтанка',
    r'программатик\s*докторпитер',
    r'программатик\s*доктор\s*питер'
]

EXCLUDE_MANAGERS = [
    'Алмазова А.', 'Василенко В.', 'Большакова М.', 'Савиных Е. Д.',
    'Пирожкова Е.', 'Селиванова А.', 'Дмитриева Д.'
]

DISCOUNT_BUCKETS = [0,5,10,15,20,25,50]

def bucket_discount(x):
    if pd.isna(x):
        return 'без скидки'
    try:
        xv = float(x)
    except:
        return 'прочие'

    if xv == 0:
        return 'без скидки'
    if xv in DISCOUNT_BUCKETS:
        return f'{int(xv)}%'
    if 40 <= xv <= 75:
        return '40–75% (нестандарты)'
    return 'прочие'


REVENUE_BUCKETS = [
    ('Менее 10 тыс. руб.', 0, 10_000),
    ('10-50 тыс. руб.', 10_000, 50_000),
    ('50-100 тыс. руб.', 50_000, 100_000),
    ('100-500 тыс. руб.', 100_000, 500_000),
    ('500 тыс. - 1 млн руб.', 500_000, 1_000_000),
    ('Более 1 млн руб.', 1_000_000, float('inf'))
]

# Проекты для исключения в общей аналитике (НО НЕ для клиентов и RFM!)
EXCLUDE_PROJECTS = ['Мероприятия (деловые)', 'Мероприятия (городские)']

# ----------- Имена колонок -----------
COL_MONTH = 'Месяц'
COL_ORDER = 'Заказ'
COL_DATE = 'Дата заказа'
COL_MANAGER = 'Менеджер'
COL_NOMEN = 'Номенклатура'
COL_VARIANT = 'Вариант номенклатуры'
COL_CLIENT = 'Клиент'
COL_CONTR = 'Контрагент'
COL_QTY = 'Кол-во'
COL_DISCOUNT_PCT = 'Скидка, %'
COL_REVENUE = 'Выручка без НДС'
COL_REVENUE_OPL = 'Выручка без НДС опл'
COL_REVENUE_FULL = 'Выручка полная без НДС'
COL_PROJECT = 'Проект'
COL_AD_TYPE = 'Тип рекламы'
COL_AD_KIND = 'Вид рекламы'
COL_POS_ORDER = 'Позиция заказа'
COL_POS_NOM = 'Позиция номенклатуры'
COL_PAY_TYPE = 'Тип оплаты'
COL_CITY = 'Город заказа'
COL_ORG = 'Организация'
COL_CLIENT_RA = 'Клиент РА'
COL_INDUSTRY_CLIENT_RA = 'Отрасли КлиентаРА'
COL_INDUSTRY_CLIENT = 'Отрасли Клиента'
COL_INDUSTRY_ADV = 'Отрасли Рекламодателя'
COL_DESCRIPTION = 'Описание'
COL_REKLAMD = 'Рекламодатель'

# Альтернативные названия типа рекламы
AD_TYPE_ALIASES = ["Тип рекламы", "Номенклатура (Тип рекламы)"]

# ----------- Загрузка файла -----------
if not os.path.exists(INPUT_XLSX):
    raise FileNotFoundError(f"Файл {INPUT_XLSX} не найден. Загрузите его в Colab: /content/")

df_raw = pd.read_excel(INPUT_XLSX, sheet_name=0, dtype=object)
df_raw.columns = df_raw.columns.map(lambda x: x.strip() if isinstance(x, str) else x)

print("Загружено строк:", len(df_raw))
print("Колонки:", list(df_raw.columns))

# ----------- ПАТЧ: корректная фильтрация "Итого" и пустых строк -----------

if COL_MONTH in df_raw.columns:
    df_raw = df_raw.loc[~df_raw[COL_MONTH].astype(str).str.strip().str.lower().eq("итого")]

df_raw = df_raw.dropna(how="all").reset_index(drop=True)

# ----------- ПАТЧ: корректный выбор колонки "Тип рекламы" -----------

for c in df_raw.columns:
    if str(c).strip() in AD_TYPE_ALIASES:
        COL_AD_TYPE = c
        break

# ----------- Готовим рабочую копию -----------

df = df_raw.copy()

# ----------- Глобальные фильтры (как раньше, мероприятия исключаются!) -----------

# Исключаем проекты (кроме версии df_for_clients)
if COL_PROJECT in df.columns:
    proj_mask = df[COL_PROJECT].fillna('').astype(str).str.strip().isin(EXCLUDE_PROJECTS)
    if proj_mask.any():
        print(f"Глобально исключено {proj_mask.sum()} строк(и) по мероприятиям")
    df = df.loc[~proj_mask].copy()

# Исключаем менеджеров глобально
if COL_MANAGER in df.columns:
    mgr_mask = df[COL_MANAGER].fillna('').astype(str).isin(EXCLUDE_MANAGERS)
    if mgr_mask.any():
        print(f"Глобально исключено {mgr_mask.sum()} строк(и) по менеджерам")
    df = df.loc[~mgr_mask].copy()

# ----------- ПАТЧ: универсальный безопасный парсер выручки -----------

def parse_money(x):
    if pd.isna(x):
        return None
    x = str(x).strip()
    x = x.replace("руб", "").replace("Руб", "")
    x = x.replace(" ", "").replace("'", "")
    if "," in x and x.count(",") == 1 and x.count(".") >= 1:
        x = x.replace(".", "").replace(",", ".")
    else:
        x = x.replace(",", ".")
    try:
        return float(x)
    except:
        return None

# ----------- df_for_projects: выручка ВСЕХ менеджеров -----------

df_for_projects = df_raw.copy()

# убираем ИТОГО и пустые строки
if COL_MONTH in df_for_projects.columns:
    df_for_projects = df_for_projects.loc[
        ~df_for_projects[COL_MONTH].astype(str).str.strip().str.lower().eq("итого")
    ]

df_for_projects = df_for_projects.dropna(how="all").reset_index(drop=True)

# парсим выручку
df_for_projects[COL_REVENUE] = df_for_projects[COL_REVENUE].apply(parse_money)

# ----------- ПАТЧ: скидки -> числа -----------

if COL_DISCOUNT_PCT in df.columns:
    df[COL_DISCOUNT_PCT] = pd.to_numeric(
        df[COL_DISCOUNT_PCT].astype(str).str.replace(",", ".", regex=False),
        errors='coerce'
    )

# ----------- ПАТЧ: корректный парсер месяца -----------

def parse_month(s):
    s = str(s).strip()
    m = re.match(r"^(\d{1,2})\.(\d{2})$", s)
    if m:
        mm = int(m.group(1))
        yy = 2000 + int(m.group(2))
        return datetime(yy, mm, 1)
    return pd.to_datetime(s, errors='coerce')

# ----------- ПАТЧ: ФОРМИРУЕМ 3 ВЕРСИИ ДАТАФРЕЙМА -----------

df_full = df.copy()
# → Полностью очищенный датасет для общей аналитики
#   (мероприятия исключены, менеджеры исключены)

df_export = df_raw.copy()
if COL_MANAGER in df_export.columns:
    df_export = df_export.loc[~df_export[COL_MANAGER].isin(EXCLUDE_MANAGERS)]
if COL_DISCOUNT_PCT in df_export.columns:
    df_export[COL_DISCOUNT_PCT] = (
        df_export[COL_DISCOUNT_PCT]
        .astype(str)
        .str.replace(',', '.', regex=False)
        .str.replace('%', '', regex=False)
        .str.strip()
    )

    df_export[COL_DISCOUNT_PCT] = pd.to_numeric(
        df_export[COL_DISCOUNT_PCT],
        errors='coerce'
    )

# → Чистая экспортная версия, но не исключает мероприятия

# ----------- ПАТЧ: df_for_clients — ключевое! -----------
# Здесь мероприятия НЕ исключаются!
df_for_clients = df_raw.copy()

df_for_clients[COL_REVENUE] = df_for_clients[COL_REVENUE].apply(parse_money)

if COL_MANAGER in df_for_clients.columns:
    df_for_clients = df_for_clients.loc[~df_for_clients[COL_MANAGER].isin(EXCLUDE_MANAGERS)]
# → Используется для Топ-Clients и RFM
# ----------- Восстановление логики выбора конечного клиента -----------

def pick_client(row):
    for c in [COL_CLIENT_RA, COL_CLIENT, COL_REKLAMD]:
        if c in row and pd.notna(row[c]) and str(row[c]).strip() != '':
            return str(row[c]).strip()
    return ''

# создаём колонку в каждом датафрейме, который используется в аналитике

for _df in [df_full, df_export, df_for_clients]:
    _df['КОНЕЧНЫЙ_КЛИЕНТ'] = _df.apply(pick_client, axis=1)
# ----------- Восстановление логики определения отрасли -----------

def pick_industry(row):
    for c in [COL_INDUSTRY_CLIENT_RA, COL_INDUSTRY_CLIENT, COL_INDUSTRY_ADV]:
        if c in row and pd.notna(row[c]) and str(row[c]).strip() != '':
            return str(row[c]).strip()
    return ''

# Добавляем ОТРАСЛЬ_КЛИЕНТА в три датафрейма
for _df in [df_full, df_export, df_for_clients]:
    _df['ОТРАСЛЬ_КЛИЕНТА'] = _df.apply(pick_industry, axis=1)

# ----------- Нормализация отраслей -----------

def classify_mrv(row):
    raw = str(row['ОТРАСЛЬ_КЛИЕНТА']).strip().lower()

    # Строительство + Недвижимость
    if any(x in raw for x in ['строит', 'строй', 'недвиж']):
        return 'Строительство + Недвижимость'

    # Подготовка текстов
    text = (
        str(row.get(COL_POS_ORDER, '') or '') + ' ' +
        str(row.get(COL_DESCRIPTION, '') or '') + ' ' +
        str(row.get(COL_NOMEN, '') or '') + ' ' +
        str(row.get('КОНЕЧНЫЙ_КЛИЕНТ', '') or '')
    ).lower()

    # Точные категории
    if raw == 'маркетинг':
        return 'Маркетинг'
    if raw == 'реклама':
        return 'Реклама'
    if raw == 'выставки':
        return 'Выставки'

    # Общая категория → уточняем
    if 'маркетинг, реклама, выставки' in raw:
        if 'выстав' in text:
            return 'Выставки'
        if 'реклам' in text:
            return 'Реклама'
        if 'маркет' in text:
            return 'Маркетинг'
        return 'Маркетинг'

    # Если пусто → определяем по контексту
    if raw in ['', 'nan', 'none']:
        if 'выстав' in text:
            return 'Выставки'
        if 'реклам' in text:
            return 'Реклама'
        if 'маркет' in text:
            return 'Маркетинг'

    # Иначе возвращаем исходное значение
    return row['ОТРАСЛЬ_КЛИЕНТА']

# Добавляем нормализованную отрасль
for _df in [df_full, df_export, df_for_clients]:
    _df['ОТРАСЛЬ_КЛИЕНТА_НОРМ'] = _df.apply(classify_mrv, axis=1)

# ----------- Категории выручки (прочие) -----------
def categorize_revenue_amount(v):
    if pd.isna(v):
        return 'Нет данных'
    try:
        v = float(v)
    except:
        return 'прочие'
    for name, lo, hi in REVENUE_BUCKETS:
        if lo <= v < hi:
            return name
    return 'прочие'

df_full['Категория выручки'] = df_full[COL_REVENUE].apply(categorize_revenue_amount)
df_export['Категория выручки'] = df_export[COL_REVENUE].apply(categorize_revenue_amount)

# ----------- Агрегаты и таблицы -----------
# Гарантируем, что revenue переменная — именно одна колонка (фикс для ValueError)
revenue_col = COL_REVENUE
if isinstance(revenue_col, (list, tuple)):
    revenue_col = revenue_col[0]

# По месяцам (используем df_full)
if COL_MONTH in df_full.columns:
    # Приводим месяц к формату 01.YYYY если строка вида '01.25' — делаем год 2025
    def parse_month(s):
        try:
            if pd.isna(s):
                return None
            s = str(s).strip()
            if '.' in s:
                mm, yy = s.split('.')
                yy = int(yy)
                if yy < 100:
                    yy = 2000 + yy
                return datetime(year=yy, month=int(mm), day=1)
            # попытаться парсить как дата
            return pd.to_datetime(s, errors='coerce')
        except:
            return None
    df_full['Дата_месяц'] = df_full[COL_MONTH].apply(parse_month)
    monthly_stats = df_full.dropna(subset=['Дата_месяц']).groupby(df_full['Дата_месяц'].dt.strftime('%m.%Y')).agg({
        revenue_col: ['sum', 'mean', 'count']
    }).round(2)
    monthly_stats.columns = ['Сумма выручки, руб.', 'Средний чек, руб.', 'Количество заказов']
    monthly_stats['Сумма выручки, тыс. руб.'] = monthly_stats['Сумма выручки, руб.'] / 1000
    monthly_stats = monthly_stats.reset_index().rename(columns={'Дата_месяц': 'Период'})

# Топ клиентов — по df_full, по 'КОНЕЧНЫЙ_КЛИЕНТ'
client_stats = df_full.groupby('КОНЕЧНЫЙ_КЛИЕНТ').agg({revenue_col: ['sum', 'mean', 'count']}).round(2)
client_stats.columns = ['Сумма выручки, руб.', 'Средний чек, руб.', 'Количество заказов']
client_stats['Сумма выручки, тыс. руб.'] = client_stats['Сумма выручки, руб.'] / 1000
client_stats = client_stats.reset_index().sort_values('Сумма выручки, тыс. руб.', ascending=False)

# Топ менеджеров — считаем по df_full, но при ранжировании исключаем упомянутых менеджеров
if COL_MANAGER in df_full.columns:
    manager_df_for_rank = df_full.loc[~df_full[COL_MANAGER].isin(EXCLUDE_MANAGERS)]
    manager_stats = manager_df_for_rank.groupby(COL_MANAGER).agg({revenue_col: ['sum', 'mean', 'count']}).round(2)
    manager_stats.columns = ['Сумма выручки, руб.', 'Средний чек, руб.', 'Количество заказов']
    manager_stats['Сумма выручки, тыс. руб.'] = manager_stats['Сумма выручки, руб.'] / 1000
    manager_stats = manager_stats.reset_index().sort_values('Сумма выручки, тыс. руб.', ascending=False)
else:
    manager_stats = None

# По отраслям (нормализованные)
industry_stats = df_full.groupby('ОТРАСЛЬ_КЛИЕНТА_НОРМ').agg({revenue_col: ['sum', 'mean', 'count']}).round(2)
industry_stats.columns = ['Сумма выручки, руб.', 'Средний чек, руб.', 'Количество заказов']
industry_stats['Сумма выручки, тыс. руб.'] = industry_stats['Сумма выручки, руб.'] / 1000
industry_stats = industry_stats.reset_index().sort_values('Сумма выручки, тыс. руб.', ascending=False)

# Категории выручки
category_stats = df_full.groupby('Категория выручки').agg({revenue_col: ['sum', 'mean', 'count']}).round(2)
category_stats.columns = ['Сумма выручки, руб.', 'Средний чек, руб.', 'Количество заказов']
category_stats['Сумма выручки, тыс. руб.'] = category_stats['Сумма выручки, руб.'] / 1000
category_stats = category_stats.reset_index().sort_values('Сумма выручки, тыс. руб.', ascending=False)

print('RAW скидки (df_export):')
print(
    df_export[COL_DISCOUNT_PCT]
    .astype(str)
    .str.strip()
    .value_counts(dropna=False)
)

# Лист 13: заказы со скидками — особая логика
discount_export = None

if COL_DISCOUNT_PCT in df_export.columns:
    disc_df = df_export.copy()

    # 1. ПАРСИНГ СКИДКИ
    disc_df['Скидка_%_число'] = (
        disc_df[COL_DISCOUNT_PCT]
        .astype(str)
        .str.replace(',', '.', regex=False)
        .str.replace('%', '', regex=False)
        .str.strip()
    )

    disc_df['Скидка_%_число'] = pd.to_numeric(
        disc_df['Скидка_%_число'],
        errors='coerce'
    )

    # 2. КАТЕГОРИЗАЦИЯ
    disc_df['Категория_скидки'] = disc_df['Скидка_%_число'].apply(bucket_discount)

    # 3. ИСКЛЮЧЕНИЕ ПРОГРАММАТИКА
    if COL_ORDER in disc_df.columns:
        p_mask = pd.Series(False, index=disc_df.index)
        for p in PROGRAMMATIC_PATTERNS:
            p_mask |= disc_df[COL_ORDER].fillna('').astype(str).str.lower().str.contains(p)
        disc_df = disc_df.loc[~p_mask].copy()

    # 4. ФОРМИРОВАНИЕ ВЫХОДНОЙ ТАБЛИЦЫ
    cols_for_discount = [
        'КОНЕЧНЫЙ_КЛИЕНТ',
        COL_ORDER,
        COL_DISCOUNT_PCT,
        revenue_col,
        COL_MANAGER,
        'Категория_скидки'
    ]
    cols_for_discount = [c for c in cols_for_discount if c in disc_df.columns]

    discount_export = disc_df[cols_for_discount].copy()
    discount_export['Выручка_тыс_руб'] = discount_export[revenue_col] / 1000

# Подготовка summary (суммарные метрики)
summary_df = pd.DataFrame({
    'Метрика': [
        'Общая выручка, тыс. руб.',
        'Средний чек, тыс. руб.',
        'Медианный чек, тыс. руб.',
        'Количество заказов',
        'Уникальных клиентов',
        'Уникальных менеджеров (все)'
    ],
    'Значение': [
        df_full[revenue_col].sum() / 1000,
        df_full[revenue_col].mean() / 1000,
        df_full[revenue_col].median() / 1000,
        len(df_full),
        df_full['КОНЕЧНЫЙ_КЛИЕНТ'].nunique(),
        df_full[COL_MANAGER].nunique() if COL_MANAGER in df_full.columns else None
    ]
})

# ----------- Добавление недостающих метрик из "средний_чек.txt" -----------

# 1. АНАЛИЗ ПО ПРОЕКТАМ (после исключения мероприятий)
print("\n" + "=" * 80)
print("АНАЛИЗ ПО ПРОЕКТАМ (в тысячах рублей)")
print("=" * 80)

if COL_PROJECT in df_full.columns:
    project_stats_detailed = df_for_projects.groupby(COL_PROJECT).agg({
    COL_REVENUE: ['sum', 'mean', 'count']
}).round(2)

    project_stats_detailed.columns = ['Сумма выручки, руб.', 'Средний чек, руб.', 'Количество заказов']
    project_stats_detailed['Сумма выручки, тыс. руб.'] = project_stats_detailed['Сумма выручки, руб.'] / 1000
    project_stats_detailed['Средний чек, тыс. руб.'] = project_stats_detailed['Средний чек, руб.'] / 1000

    project_stats_detailed = project_stats_detailed.reset_index().sort_values('Сумма выручки, тыс. руб.', ascending=False)

    print("Топ-10 проектов по выручке:")
    print(project_stats_detailed.head(10).to_string(index=False))

# 2. АНАЛИЗ ПО ТИПАМ РЕКЛАМЫ
print("\n" + "=" * 80)
print("АНАЛИЗ ПО ТИПАМ РЕКЛАМЫ (в тысячах рублей)")
print("=" * 80)

if COL_AD_TYPE in df_full.columns:
    ad_type_stats_detailed = df_full.groupby(COL_AD_TYPE).agg({
        revenue_col: ['sum', 'mean', 'count']
    }).round(2)

    ad_type_stats_detailed.columns = ['Сумма выручки, руб.', 'Средний чек, руб.', 'Количество заказов']
    ad_type_stats_detailed['Сумма выручки, тыс. руб.'] = ad_type_stats_detailed['Сумма выручки, руб.'] / 1000
    ad_type_stats_detailed['Средний чек, тыс. руб.'] = ad_type_stats_detailed['Средний чек, руб.'] / 1000

    ad_type_stats_detailed = ad_type_stats_detailed.reset_index().sort_values('Сумма выручки, тыс. руб.', ascending=False)

    print("Анализ по типам рекламы:")
    print(ad_type_stats_detailed.head(10).to_string(index=False))

# 3. СРАВНЕНИЕ С ИСХОДНЫМИ ДАННЫМИ
print("\n" + "=" * 80)
print("СРАВНЕНИЕ: ИСХОДНЫЕ ДАННЫЕ И ПОСЛЕ ФИЛЬТРАЦИИ")
print("=" * 80)

# Рассчитываем метрики для исходных данных (после очистки от Итого)
df_raw_cleaned = df_raw.loc[~df_raw[COL_MONTH].astype(str).str.strip().str.lower().isin(['итого', 'nan', 'none'])]
df_raw_cleaned[COL_REVENUE] = pd.to_numeric(df_raw_cleaned[COL_REVENUE].astype(str).str.replace(r"[^\d\-,\.]", "", regex=True).str.replace(",", ".", regex=False), errors='coerce')

comparison_metrics = pd.DataFrame({
    'Показатель': [
        'Количество заказов',
        'Общая выручка, тыс. руб.',
        'Средний чек, тыс. руб.',
        'Медианный чек, тыс. руб.',
        'Минимальный чек, тыс. руб.',
        'Максимальный чек, тыс. руб.'
    ],
    'Исходные данные': [
        len(df_raw_cleaned),
        df_raw_cleaned[COL_REVENUE].sum() / 1000,
        df_raw_cleaned[COL_REVENUE].mean() / 1000,
        df_raw_cleaned[COL_REVENUE].median() / 1000,
        df_raw_cleaned[COL_REVENUE].min() / 1000,
        df_raw_cleaned[COL_REVENUE].max() / 1000
    ],
    'После фильтров': [
        len(df_full),
        df_full[revenue_col].sum() / 1000,
        df_full[revenue_col].mean() / 1000,
        df_full[revenue_col].median() / 1000,
        df_full[revenue_col].min() / 1000,
        df_full[revenue_col].max() / 1000
    ]
})

comparison_metrics['Разница'] = comparison_metrics['После фильтров'] - comparison_metrics['Исходные данные']
comparison_metrics['Изменение, %'] = (comparison_metrics['Разница'] / comparison_metrics['Исходные данные']) * 100

print(comparison_metrics.to_string(index=False))

# 5. ДЕТАЛЬНЫЙ АНАЛИЗ СКИДОК
print("\n" + "=" * 80)
print("ДЕТАЛЬНЫЙ АНАЛИЗ СКИДОК И ЦЕНОВОЙ ПОЛИТИКИ")
print("=" * 80)

if COL_DISCOUNT_PCT in df_full.columns:
    df_full['Скидка_%_число'] = pd.to_numeric(df_full[COL_DISCOUNT_PCT], errors='coerce')

    discount_stats_detailed = {
        'Заказов со скидкой': df_full['Скидка_%_число'].notna().sum(),
        'Заказов без скидки': df_full['Скидка_%_число'].isna().sum(),
        'Средняя скидка (%)': df_full['Скидка_%_число'].mean(),
        'Медианная скидка (%)': df_full['Скидка_%_число'].median(),
        'Максимальная скидка (%)': df_full['Скидка_%_число'].max(),
        'Минимальная скидка (%)': df_full['Скидка_%_число'].min()
    }

    discount_detailed_df = pd.DataFrame(list(discount_stats_detailed.items()), columns=['Показатель', 'Значение'])
    print(discount_detailed_df.to_string(index=False))

    # Анализ скидок по менеджерам
    if COL_MANAGER in df_full.columns:
        discount_by_manager = df_full.groupby(COL_MANAGER).agg({
            'Скидка_%_число': ['mean', 'count'],
            revenue_col: 'sum'
        }).round(2)

        if discount_by_manager.shape[0] > 0:
            print("\nСкидки по менеджерам:")
            discount_by_manager.columns = ['Средняя скидка, %', 'Кол-во скидок', 'Выручка, руб.']
            discount_by_manager['Выручка, тыс. руб.'] = discount_by_manager['Выручка, руб.'] / 1000
            discount_by_manager = discount_by_manager.reset_index().sort_values('Средняя скидка, %', ascending=False)
            print(discount_by_manager.head(10).to_string(index=False))

# 6. RFM-АНАЛИЗ КЛИЕНТОВ
print("\n" + "=" * 80)
print("RFM-АНАЛИЗ КЛИЕНТОВ")
print("=" * 80)

# ----------------- RFM: расширенный блок -----------------
# Ожидается, что перед этим df_full уже сформирован и содержит 'КОНЕЧНЫЙ_КЛИЕНТ' и колонку с датой заказа (COL_DATE)
if COL_DATE in df_full.columns and 'КОНЕЧНЫЙ_КЛИЕНТ' in df_full.columns:
    try:
        # Преобразуем дату заказа
        df_full['Дата_заказа'] = pd.to_datetime(df_full[COL_DATE], errors='coerce')

        # Текущая дата — используем максимальную дату в данных
        current_date = df_full['Дата_заказа'].max()

        # Сгруппируем по клиенту и рассчитаем базовые метрики
        rfm_data = df_full.groupby('КОНЕЧНЫЙ_КЛИЕНТ').agg({
            'Дата_заказа': 'max',    # последняя покупка -> для Recency
            COL_ORDER: 'count',      # частота (кол-во заказов)
            revenue_col: 'sum'       # денежная ценность
        }).reset_index().rename(columns={
            'Дата_заказа': 'Последняя_покупка',
            COL_ORDER: 'Частота',
            revenue_col: 'Денежная_ценность_руб'
        })

        # Вычисляем числовые RFM метрики
        rfm_data['Recency_days'] = (current_date - rfm_data['Последняя_покупка']).dt.days
        rfm_data['Frequency_orders'] = rfm_data['Частота']
        rfm_data['Monetary_thousands'] = rfm_data['Денежная_ценность_руб'] / 1000.0

        # Удаляем клиентов без даты/значений
        rfm_data = rfm_data.dropna(subset=['Recency_days', 'Frequency_orders', 'Monetary_thousands'])

        # Квантили для разбиения (используются для присвоения рейтингов 1..4)
        quantiles = rfm_data[['Recency_days', 'Frequency_orders', 'Monetary_thousands']].quantile([0.25, 0.5, 0.75])
        q_rec = quantiles['Recency_days']
        q_f = quantiles['Frequency_orders']
        q_m = quantiles['Monetary_thousands']

        # Функция рейтингования (R: меньшие лучше — инвертируем логику при применении)
        def score_r(x):
            if x <= q_rec[0.25]:
                return 4
            elif x <= q_rec[0.5]:
                return 3
            elif x <= q_rec[0.75]:
                return 2
            else:
                return 1

        def score_f(x):
            if x <= q_f[0.25]:
                return 1
            elif x <= q_f[0.5]:
                return 2
            elif x <= q_f[0.75]:
                return 3
            else:
                return 4

        def score_m(x):
            if x <= q_m[0.25]:
                return 1
            elif x <= q_m[0.5]:
                return 2
            elif x <= q_m[0.75]:
                return 3
            else:
                return 4

        rfm_data['R'] = rfm_data['Recency_days'].apply(score_r)
        rfm_data['F'] = rfm_data['Frequency_orders'].apply(score_f)
        rfm_data['M'] = rfm_data['Monetary_thousands'].apply(score_m)

        rfm_data['RFM_Score'] = rfm_data[['R', 'F', 'M']].sum(axis=1)

        # Сегментация (тот же набор, что и раньше)
        def segment_customer(score):
            if score >= 10:
                return 'Champions'
            elif score >= 8:
                return 'Loyal Customers'
            elif score >= 6:
                return 'Potential Loyalists'
            elif score >= 4:
                return 'At Risk'
            else:
                return 'Hibernating'

        rfm_data['Segment'] = rfm_data['RFM_Score'].apply(segment_customer)

        # Формируем расширенное текстовое объяснение причины попадания
        def build_reason(row):
            reasons = []
            # Recency
            if row['R'] >= 3:
                reasons.append(f"Недавняя покупка ({int(row['Recency_days'])} дн.)")
            else:
                reasons.append(f"Последняя покупка давняя ({int(row['Recency_days'])} дн.)")
            # Frequency
            if row['F'] >= 3:
                reasons.append(f"Высокая частота ({int(row['Frequency_orders'])} заказов)")
            else:
                reasons.append(f"Низкая/средняя частота ({int(row['Frequency_orders'])} заказов)")
            # Monetary
            if row['M'] >= 3:
                reasons.append(f"Высокая сумма ({row['Monetary_thousands']:,.1f} тыс. руб.)")
            else:
                reasons.append(f"Низкая/средняя сумма ({row['Monetary_thousands']:,.1f} тыс. руб.)")

            # Краткая итоговая подсказка по сегменту
            segment_hint = row['Segment']
            return "; ".join(reasons) + f" → Отнесён к сегменту: {segment_hint}"

        rfm_data['Причина_сегментации'] = rfm_data.apply(build_reason, axis=1)

        # Создаем summary по сегментам
        segment_stats = rfm_data.groupby('Segment').agg({
            'КОНЕЧНЫЙ_КЛИЕНТ': 'count',
            'Monetary_thousands': 'sum',
            'Frequency_orders': 'mean',
            'Recency_days': 'mean'
        }).reset_index()

        # Топ клиентов по RFM
        top_rfm = rfm_data[['КОНЕЧНЫЙ_КЛИЕНТ','R','F','M','RFM_Score','Segment','Recency_days','Frequency_orders','Monetary_thousands','Причина_сегментации']].sort_values('RFM_Score', ascending=False).head(20)

        print("RFM: топ клиентов по RFM-оценке (пример):")
        print(top_rfm.head(10).to_string(index=False))

    except Exception as e:
        print(f"RFM-анализ не удался: {e}")

# 7. СЕЗОННЫЙ АНАЛИЗ ПРОДАЖ
print("\n" + "=" * 80)
print("СЕЗОННЫЙ АНАЛИЗ ПРОДАЖ")
print("=" * 80)

if COL_DATE in df_full.columns:
    df_full['Дата_заказа'] = pd.to_datetime(df_full[COL_DATE], errors='coerce')
    df_full['Месяц_число'] = df_full['Дата_заказа'].dt.month
    df_full['Квартал'] = df_full['Дата_заказа'].dt.quarter
    df_full['Сезон'] = df_full['Месяц_число'].apply(lambda x:
        'Зима' if x in [12, 1, 2] else
        'Весна' if x in [3, 4, 5] else
        'Лето' if x in [6, 7, 8] else 'Осень'
    )

    seasonal_stats = df_full.groupby('Сезон').agg({
        revenue_col: ['sum', 'mean', 'count'],
        'КОНЕЧНЫЙ_КЛИЕНТ': 'nunique'
    }).round(2)

    seasonal_stats.columns = ['Выручка, руб.', 'Средний чек, руб.', 'Кол-во заказов', 'Уникальных клиентов']
    seasonal_stats['Выручка, тыс. руб.'] = seasonal_stats['Выручка, руб.'] / 1000
    seasonal_stats['Средний чек, тыс. руб.'] = seasonal_stats['Средний чек, руб.'] / 1000

    print("Выручка по сезонам:")
    print(seasonal_stats.reset_index().to_string(index=False))

    # Анализ по кварталам
    quarterly_stats = df_full.groupby('Квартал').agg({
        revenue_col: ['sum', 'count']
    }).round(2)

    quarterly_stats.columns = ['Выручка, руб.', 'Кол-во заказов']
    quarterly_stats['Выручка, тыс. руб.'] = quarterly_stats['Выручка, руб.'] / 1000

    print("\nВыручка по кварталам:")
    print(quarterly_stats.reset_index().to_string(index=False))

    # Коэффициент сезонности
    avg_quarterly = quarterly_stats['Выручка, тыс. руб.'].mean()
    quarterly_stats['Коэф. сезонности'] = quarterly_stats['Выручка, тыс. руб.'] / avg_quarterly
    print("\nКоэффициенты сезонности (1 = среднее значение):")
    print(quarterly_stats[['Коэф. сезонности']].reset_index().to_string(index=False))

# 8. АНАЛИЗ ЛОЯЛЬНОСТИ И ПОВТОРНЫХ ПОКУПОК
print("\n" + "=" * 80)
print("АНАЛИЗ ЛОЯЛЬНОСТИ И ПОВТОРНЫХ ПОКУПОК")
print("=" * 80)

client_order_stats = df_full.groupby('КОНЕЧНЫЙ_КЛИЕНТ').agg({
    COL_ORDER: 'count',
    revenue_col: 'sum'
}).round(2)

client_order_stats.columns = ['Количество заказов', 'Общая выручка, руб.']
client_order_stats['Общая выручка, тыс. руб.'] = client_order_stats['Общая выручка, руб.'] / 1000

# Распределение клиентов по количеству заказов
order_frequency = client_order_stats['Количество заказов'].value_counts().sort_index()
order_freq_df = pd.DataFrame({
    'Количество заказов': order_frequency.index,
    'Количество клиентов': order_frequency.values,
    'Доля клиентов, %': (order_frequency.values / order_frequency.sum() * 100).round(1)
})

print("Распределение клиентов по количеству заказов:")
print(order_freq_df.to_string(index=False))

# Процент повторных клиентов
repeat_clients = len(client_order_stats[client_order_stats['Количество заказов'] > 1])
total_clients = len(client_order_stats)
repeat_rate = (repeat_clients / total_clients * 100) if total_clients > 0 else 0

print(f"\nМетрики лояльности:")
print(f"Всего клиентов: {total_clients}")
print(f"Повторных клиентов: {repeat_clients}")
print(f"Процент повторных клиентов: {repeat_rate:.1f}%")
print(f"Клиенты с 1 заказом: {len(client_order_stats[client_order_stats['Количество заказов'] == 1])}")
print(f"Клиенты с 2+ заказами: {len(client_order_stats[client_order_stats['Количество заказов'] >= 2])}")
print(f"Клиенты с 5+ заказами: {len(client_order_stats[client_order_stats['Количество заказов'] >= 5])}")

# Выручка от новых vs повторных клиентов
if total_clients > 0:
    new_clients_revenue = client_order_stats[client_order_stats['Количество заказов'] == 1]['Общая выручка, тыс. руб.'].sum()
    repeat_clients_revenue = client_order_stats[client_order_stats['Количество заказов'] > 1]['Общая выручка, тыс. руб.'].sum()
    total_revenue = client_order_stats['Общая выручка, тыс. руб.'].sum()

    print(f"\nРаспределение выручки:")
    print(f"Выручка от новых клиентов: {new_clients_revenue:,.1f} тыс. руб. ({new_clients_revenue/total_revenue*100:.1f}%)")
    print(f"Выручка от повторных клиентов: {repeat_clients_revenue:,.1f} тыс. руб. ({repeat_clients_revenue/total_revenue*100:.1f}%)")

# Создаем таблицу для экспорта по лояльности
loyalty_summary_export = pd.DataFrame({
    'Метрика': [
        'Всего клиентов',
        'Повторных клиентов (2+ заказов)',
        'Процент повторных клиентов, %',
        'Клиенты с 1 заказом',
        'Клиенты с 2+ заказами',
        'Клиенты с 5+ заказами',
        'Выручка от новых клиентов, тыс. руб.',
        'Выручка от повторных клиентов, тыс. руб.',
        'Доля выручки от новых клиентов, %',
        'Доля выручки от повторных клиентов, %'
    ],
    'Значение': [
        total_clients,
        repeat_clients,
        repeat_rate,
        len(client_order_stats[client_order_stats['Количество заказов'] == 1]),
        len(client_order_stats[client_order_stats['Количество заказов'] >= 2]),
        len(client_order_stats[client_order_stats['Количество заказов'] >= 5]),
        new_clients_revenue if total_clients > 0 else 0,
        repeat_clients_revenue if total_clients > 0 else 0,
        (new_clients_revenue/total_revenue*100) if total_clients > 0 and total_revenue > 0 else 0,
        (repeat_clients_revenue/total_revenue*100) if total_clients > 0 and total_revenue > 0 else 0
    ]
})

# 9. РАСШИРЕННЫЙ СВОДНЫЙ ОТЧЕТ
print("\n" + "=" * 80)
print("РАСШИРЕННЫЙ СВОДНЫЙ ОТЧЕТ")
print("=" * 80)

# Определяем самый прибыльный месяц
best_month = None
best_month_revenue = 0
if 'monthly_stats' in locals() and monthly_stats is not None and len(monthly_stats) > 0:
    best_month_row = monthly_stats.loc[monthly_stats['Сумма выручки, тыс. руб.'].idxmax()]
    best_month = best_month_row['Период']
    best_month_revenue = best_month_row['Сумма выручки, тыс. руб.']

# Определяем самого прибыльного менеджера
best_manager = None
best_manager_revenue = 0
if manager_stats is not None and len(manager_stats) > 0:
    best_manager_row = manager_stats.iloc[0]
    best_manager = best_manager_row[COL_MANAGER]
    best_manager_revenue = best_manager_row['Сумма выручки, тыс. руб.']

# Определяем самого прибыльного клиента
best_client = None
best_client_revenue = 0
if len(client_stats) > 0:
    best_client_row = client_stats.iloc[0]
    best_client = best_client_row['КОНЕЧНЫЙ_КЛИЕНТ']
    best_client_revenue = best_client_row['Сумма выручки, тыс. руб.']

extended_summary = pd.DataFrame({
    'Метрика': [
        'Общая выручка, тыс. руб.',
        'Средний чек, тыс. руб.',
        'Медианный чек, тыс. руб.',
        'Количество заказов',
        'Уникальных клиентов',
        'Уникальных менеджеров (все)',
        'Уникальных проектов',
        'Самый прибыльный месяц',
        'Выручка в самый прибыльный месяц, тыс. руб.',
        'Самый прибыльный менеджер',
        'Выручка топ-менеджера, тыс. руб.',
        'Самый прибыльный клиент',
        'Выручка топ-клиента, тыс. руб.',
        'Процент повторных клиентов',
        'Средняя скидка, %',
        'Количество сезонов с данными'
    ],
    'Значение': [
        df_full[revenue_col].sum() / 1000,
        df_full[revenue_col].mean() / 1000,
        df_full[revenue_col].median() / 1000,
        len(df_full),
        df_full['КОНЕЧНЫЙ_КЛИЕНТ'].nunique(),
        df_full[COL_MANAGER].nunique() if COL_MANAGER in df_full.columns else None,
        df_full[COL_PROJECT].nunique() if COL_PROJECT in df_full.columns else None,
        best_month,
        best_month_revenue,
        best_manager,
        best_manager_revenue,
        best_client[:30] + '...' if best_client and len(best_client) > 30 else best_client,
        best_client_revenue,
        f"{repeat_rate:.1f}%",
        df_full['Скидка_%_число'].mean() if 'Скидка_%_число' in df_full.columns else None,
        df_full['Сезон'].nunique() if 'Сезон' in df_full.columns else None
    ]
})

print(extended_summary.to_string(index=False))

# 10. ПРОГНОЗИРОВАНИЕ (если есть временной ряд)
print("\n" + "=" * 80)
print("ПРОГНОЗИРОВАНИЕ НА СЛЕДУЮЩИЙ ПЕРИОД")
print("=" * 80)

if 'monthly_stats' in locals() and monthly_stats is not None and len(monthly_stats) >= 3:
    try:
        # Используем временной ряд из monthly_stats
        time_series = monthly_stats.set_index('Период')['Сумма выручки, тыс. руб.']

        # Простой линейный прогноз
        months = np.arange(len(time_series))
        revenue_values = time_series.values

        # Линейная регрессия для прогноза
        coeff = np.polyfit(months, revenue_values, 1)

        # Прогноз на следующий месяц
        next_month = len(months)
        forecast = coeff[0] * next_month + coeff[1]

        # Рассчитываем тренд
        trend_direction = "растет" if coeff[0] > 0 else "падает"
        trend_strength = abs(coeff[0]) / revenue_values.mean() * 100

        print(f"Тренд выручки: {trend_direction}")
        print(f"Сила тренда: {trend_strength:.1f}% в месяц")
        print(f"Прогноз на следующий месяц: {forecast:,.1f} тыс. руб.")

        # Рекомендации
        print("\nРекомендации на основе анализа:")
        if coeff[0] > 0:
            print("✅ Тренд положительный - продолжайте текущую стратегию")
        else:
            print("⚠️  Тренд отрицательный - нужны корректирующие меры")

    except Exception as e:
        print(f"Прогнозирование не удалось: {e}")
else:
    print("Недостаточно данных для прогнозирования (нужно минимум 3 месяца)")

# -------------- СОБИРАЕМ ВСЕ ТАБЛИЦЫ ДЛЯ ЭКСПОРТА --------------
export_data = {}

# Основные таблицы
if 'monthly_stats' in locals() and monthly_stats is not None:
    export_data['01_Месячная_статистика'] = monthly_stats

if 'client_stats' in locals() and client_stats is not None:
    export_data['02_Топ_клиентов'] = client_stats.head(50)

if 'manager_stats' in locals() and manager_stats is not None:
    export_data['03_Топ_менеджеров'] = manager_stats.head(30)

if 'industry_stats' in locals() and industry_stats is not None:
    export_data['04_Топ_отраслей'] = industry_stats.head(30)

if 'category_stats' in locals() and category_stats is not None:
    export_data['05_Категории_выручки'] = category_stats

if 'summary_df' in locals() and summary_df is not None:
    export_data['06_Сводная_таблица'] = summary_df

# Дополнительные таблицы анализа
if 'project_stats_detailed' in locals() and project_stats_detailed is not None:
    export_data['07_Топ_проектов'] = project_stats_detailed.head(20)

if 'ad_type_stats_detailed' in locals() and ad_type_stats_detailed is not None:
    export_data['08_Топ_типов_рекламы'] = ad_type_stats_detailed.head(20)

if 'comparison_metrics' in locals() and comparison_metrics is not None:
    export_data['09_Сравнение_фильтров'] = comparison_metrics

if 'discount_detailed_df' in locals() and discount_detailed_df is not None:
    export_data['10_Статистика_скидок'] = discount_detailed_df

if 'segment_stats' in locals() and segment_stats is not None:
    export_data['11_RFM_сегменты'] = segment_stats

if 'top_rfm' in locals() and top_rfm is not None:
    export_data['12_RFM_топ_клиенты'] = top_rfm

if 'discount_export' in locals() and discount_export is not None:
    export_data['13_Заказы_со_скидками'] = discount_export

if 'seasonal_stats' in locals() and seasonal_stats is not None:
    export_data['14_Сезонный_анализ'] = seasonal_stats.reset_index()

if 'quarterly_stats' in locals() and quarterly_stats is not None:
    export_data['15_Кварталы'] = quarterly_stats.reset_index()

if 'loyalty_summary_export' in locals() and loyalty_summary_export is not None:
    export_data['16_Лояльность_клиентов'] = loyalty_summary_export

if 'order_freq_df' in locals() and order_freq_df is not None:
    export_data['17_Распределение_клиентов'] = order_freq_df

if 'workgroup_stats' in locals() and workgroup_stats is not None:
    export_data['18_Рабочие_группы'] = workgroup_stats

if 'extended_summary' in locals() and extended_summary is not None:
    export_data['19_Расширенный_сводный'] = extended_summary

if 'discount_by_manager' in locals() and discount_by_manager is not None:
    export_data['20_Скидки_по_менеджерам'] = discount_by_manager

print("\n" + "=" * 80)
print(f"ПОДГОТОВЛЕНО ДЛЯ ЭКСПОРТА: {len(export_data)} ЛИСТОВ")
print("=" * 80)

# -------------- Сохранение в Excel --------------
from openpyxl.utils import get_column_letter
with pd.ExcelWriter(OUTPUT_XLSX, engine='openpyxl') as writer:
    for sheet_name, df_sheet in export_data.items():
        safe_name = sheet_name[:31]
        try:
            df_sheet.to_excel(writer, sheet_name=safe_name, index=False)
            ws = writer.sheets[safe_name]
            # автоширина столбцов
            for col_idx, col in enumerate(df_sheet.columns, 1):
                max_len = max(df_sheet[col].astype(str).map(len).max(), len(str(col))) + 2
                ws.column_dimensions[get_column_letter(col_idx)].width = min(max_len, 60)
            print(f"Сохранён лист: {safe_name} ({len(df_sheet)} строк)")
        except Exception as e:
            print(f"Ошибка при сохранении листа {safe_name}: {e}")

print("\n" + "=" * 80)
print(f"ФАЙЛ УСПЕШНО СОХРАНЁН: {OUTPUT_XLSX}")
print("=" * 80)

# Попытка скачать автоматически
try:
    files.download(OUTPUT_XLSX)
except Exception as e:
    print("Авто-скачивание не удалось. Файл доступен в рабочей директории Colab:", OUTPUT_XLSX)